"""Change wrong_answers field to JSON

Revision ID: 28ca020e531b
Revises: 644a3cfdfd55
Create Date: 2024-09-24 15:47:16.379626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ca020e531b'
down_revision: Union[str, None] = '644a3cfdfd55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'wrong_answers',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'wrong_answers',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
