"""Add image_url field to Task model

Revision ID: 56f29937265c
Revises: b19b356af0c9
Create Date: 2024-09-21 22:25:19.619596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f29937265c'
down_revision: Union[str, None] = 'b19b356af0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'image_url')
    # ### end Alembic commands ###
