"""Make short_description nullable

Revision ID: 644a3cfdfd55
Revises: b36f941b9f06
Create Date: 2024-09-23 23:54:35.517195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644a3cfdfd55'
down_revision: Union[str, None] = 'b36f941b9f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('short_description', sa.Text(), nullable=True))
    op.alter_column('tasks', 'explanation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tasks', 'resource_link',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tasks', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index('ix_tasks_topic', table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_topic', 'tasks', ['topic'], unique=False)
    op.alter_column('tasks', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('tasks', 'resource_link',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tasks', 'explanation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('tasks', 'short_description')
    # ### end Alembic commands ###
