"""Add language column to groups

Revision ID: 9f7c683c53b2
Revises: 6e3f4d5590c4
Create Date: 2024-09-27 04:11:00.240706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f7c683c53b2'
down_revision: Union[str, None] = '6e3f4d5590c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'language')
    # ### end Alembic commands ###
