"""Add subtopic field to Task

Revision ID: b36f941b9f06
Revises: 56f29937265c
Create Date: 2024-09-23 03:56:09.841748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36f941b9f06'
down_revision: Union[str, None] = '56f29937265c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('subtopic', sa.String(), nullable=True))
    op.alter_column('tasks', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tasks', 'image_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'image_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('tasks', 'topic',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('tasks', 'subtopic')
    # ### end Alembic commands ###
